[package]
name = "GeoMath"
version = "0.1.0"
authors = ["mateusfg7 <mateusfelipefg77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
